#############################################################################################################
# Base image                                                                                                #
# - I have trouble accessing the Fortran compiler with the intel/oneapi:2024.2.1-0-devel-rockylinux9 image; #
# - So I decide to build intel-oneapi-compilers from source using Spack; install other packages;            #
# - Also I want to test a different OS system (currently I have Ubuntu for NVHPC, OpenSUSE for GNU)         #
#############################################################################################################
FROM almalinux:9.6 AS spack_base

ENV DEBIAN_FRONTEND=noninteractive

SHELL ["/bin/bash", "-c"]

WORKDIR /opt

# Install python3.13 (needed for git-fleximod) and git as prerequisite for Spack
# Install the basic compilers (gcc/11.5.0) to build other packages below
RUN dnf -y update && \
    dnf -y groupinstall "Development Tools" && \
    dnf -y install epel-release && \
    dnf -y install bzip2 bzip2-devel xz xz-devel gmp-devel mpfr-devel libmpc-devel zlib-devel && \
    dnf -y install python3.13 python3.13-devel python3.13-pip && \
    dnf -y install git make wget gzip perl unzip curl pkg-config --allowerasing && \
    dnf -y install gcc-gfortran && \
    dnf clean all && \
    rm -rf /var/cache/dnf

RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.13 80 && \
    update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.13 80

# Install AWS CLI v2 for AlmaLinux 9.6
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install && \
    rm -rf awscliv2.zip aws && \
    aws --version

# Clone Spack with tag v1.1.0
RUN git clone --depth=2 --branch v1.1.0 https://github.com/spack/spack.git

########################
# Build intel compiler #
########################
FROM spack_base AS intel_compiler

# Install the Intel compiler
RUN . /opt/spack/share/spack/setup-env.sh && \
    spack install intel-oneapi-compilers@2024.2.1 && \
    update-alternatives --install /usr/bin/icpx icpx $(spack location -i intel-oneapi-compilers@2024.2.1)/compiler/2024.2/bin/icpx 120 && \
    update-alternatives --install /usr/bin/icx icx $(spack location -i intel-oneapi-compilers@2024.2.1)/compiler/2024.2/bin/icx 120 && \
    update-alternatives --install /usr/bin/ifort ifort $(spack location -i intel-oneapi-compilers@2024.2.1)/compiler/2024.2/bin/ifort 120 && \
    mkdir -p /usr/local/intel-oneapi-compiler && \
    ln -s $(spack location -i intel-oneapi-compilers@2024.2.1)/compiler/2024.2 /usr/local/intel-oneapi-compiler/2024.2

########################
# Build libxml2, cmake #
########################
FROM intel_compiler AS xml2_cmake
    
# Install xmllint that is required by CIME
# Somehow libxml2 will be built by gcc anyway during other stage, so we just use gcc here to avoid confliction
RUN . /opt/spack/share/spack/setup-env.sh && \
    spack install libxml2@2.13.5 %gcc && \
    ln -s $(spack location -i libxml2@2.13.5)/bin/xmllint /usr/local/bin/xmllint

# Spack may not find cmake3.31.8
RUN curl -L -O https://github.com/Kitware/CMake/releases/download/v3.31.8/cmake-3.31.8-linux-x86_64.tar.gz && \
    tar -zxvf cmake-3.31.8-linux-x86_64.tar.gz --strip-components=1 -C /usr/local && \
    rm -f cmake-3.31.8-linux-x86_64.tar.gz

#########################
# Build ucx and openmpi #
#########################
FROM xml2_cmake AS ucx_openmpi

# Set the Intel compilers as externals to avoid building them from source
RUN cat <<'EOF' > /root/.spack/packages.yaml
packages:
  intel-oneapi-compilers:
    buildable: false
    externals:
    - spec: intel-oneapi-compilers@2024.2.1 languages:='c,c++,fortran'
      prefix: /usr/local/intel-oneapi-compiler/2024.2
      extra_attributes:
        compilers:
          c: /usr/local/intel-oneapi-compiler/2024.2/bin/icx
          cxx: /usr/local/intel-oneapi-compiler/2024.2/bin/icpx
          fortran: /usr/local/intel-oneapi-compiler/2024.2/bin/ifort
  gcc:
    externals:
    - spec: gcc@11.5.0 languages:='c,c++,fortran'
      prefix: /usr
      extra_attributes:
        compilers:
          c: /usr/bin/gcc
          cxx: /usr/bin/g++
          fortran: /usr/bin/gfortran
EOF

# Tell Spack to scan the OS for Python/CMake and never compile it from source
RUN . /opt/spack/share/spack/setup-env.sh && \
    spack external find --not-buildable python cmake

RUN . /opt/spack/share/spack/setup-env.sh && \
    spack install ucx@1.18.1 %intel-oneapi-compilers@2024.2.1

RUN . /opt/spack/share/spack/setup-env.sh && \
    spack install openmpi@5.0.8 fabrics=cma,ucx %intel-oneapi-compilers@2024.2.1 ^ucx@1.18.1 && \
    ln -s $(spack location -i openmpi@5.0.8) /usr/local/openmpi

#############
# Build MKL #
#############
FROM ucx_openmpi AS mkl

RUN . /opt/spack/share/spack/setup-env.sh && \
    spack install intel-oneapi-mkl@2024.2.2 %intel-oneapi-compilers@2024.2.1 ^openmpi@5.0.8 && \
    ln -s $(spack location -i intel-oneapi-mkl@2024.2.2)/mkl/2024.2 /usr/local/mkl

#########################
# Build parallel-netcdf #
#########################
FROM mkl AS parallel_netcdf

RUN . /opt/spack/share/spack/setup-env.sh && \
    spack install parallel-netcdf@1.14.0 +cxx +fortran +pic +shared %intel-oneapi-compilers@2024.2.1 ^openmpi@5.0.8 && \
    ln -s $(spack location -i parallel-netcdf@1.14.0) /usr/local/pnetcdf

################
# Build netCDF #
################
FROM parallel_netcdf AS netcdf

RUN . /opt/spack/share/spack/setup-env.sh && \
    spack install netcdf-c@4.9.2 %intel-oneapi-compilers@2024.2.1 ^openmpi@5.0.8 ^parallel-netcdf@1.14.0 && \
    ln -s $(spack location -i netcdf-c@4.9.2) /usr/local/netcdf_c

# Install netcdf-fortran; it will install the netcdf-c and openmpi dependency by default
RUN . /opt/spack/share/spack/setup-env.sh && \
    spack install netcdf-fortran@4.6.1 %intel-oneapi-compilers@2024.2.1 ^netcdf-c@4.9.2 ^openmpi@5.0.8 && \
    ln -s $(spack location -i netcdf-fortran@4.6.1) /usr/local/netcdf_fortran

# Symlink the netcdf-c and netcdf-fortran installation directories to /usr/local so that CMake find_package works in a CAM build
RUN . /opt/spack/share/spack/setup-env.sh && \
    spack view symlink -i /usr/local netcdf-c netcdf-fortran

#############
# Build PIO #
#############
FROM netcdf AS parallelio

# Install parallelio; it will install the parallel-netcdf dependency by default
RUN . /opt/spack/share/spack/setup-env.sh && \
    spack install parallelio@2.6.6 +pnetcdf +fortran +mpi +shared +ncint %intel-oneapi-compilers@2024.2.1 ^parallel-netcdf@1.14.0 && \
    ln -s $(spack location -i parallelio@2.6.6) /usr/local/pio

##############
# Build ESMF #
##############
FROM parallelio AS esmf

# Use toolchains mechanism to set the Intel compilers as the default compilers for ESMF
RUN cat <<'EOF' > /root/.spack/toolchains.yaml
toolchains:
  intel-oneapi-2024:
    - spec: '%c=intel-oneapi-compilers@2024.2.1'
      when: '%c'
    - spec: '%cxx=intel-oneapi-compilers@2024.2.1'
      when: '%cxx'
    - spec: '%fortran=intel-oneapi-compilers@2024.2.1'
      when: '%fortran'
EOF

# Install ESMF; it will install its parallelio and parallel-netcdf dependencies by default
RUN . /opt/spack/share/spack/setup-env.sh && \
    spack install "esmf@8.8.1 +pnetcdf +mpi +shared %intel-oneapi-2024 ^parallelio@2.6.6 ^parallel-netcdf@1.14.0" && \
    ln -s $(spack location -i esmf@8.8.1) /usr/local/esmf

################
# Build LAPACK #
################
FROM esmf AS final_image

RUN . /opt/spack/share/spack/setup-env.sh && \
    spack install netlib-lapack@3.12.1 %intel-oneapi-compilers@2024.2.1 && \
    ln -s $(spack location -i netlib-lapack@3.12.1) /usr/local/lapack

################################################
# Set up environment variables for CI workflow #
################################################
ENV CXX=icpx
ENV CC=icx
ENV FC=ifort
ENV MPI_ROOT="/usr/local/openmpi"
ENV NETCDF_C_PATH="/usr/local/netcdf_c"
ENV NETCDF_FORTRAN_PATH="/usr/local/netcdf_fortran"
ENV PNETCDF="/usr/local/pnetcdf"
ENV PIO="/usr/local/pio"
ENV ESMFMKFILE="/usr/local/esmf/lib/esmf.mk"
ENV LAPACK="/usr/local/lapack"
ENV PIO_VERSION_MAJOR=2
ENV PIO_TYPENAME_VALID_VALUES="netcdf, pnetcdf, netcdf4c, netcdf4p"
ENV MKLROOT="/usr/local/mkl"
ENV PATH="/usr/local:/usr/local/bin:$MPI_ROOT/bin:${PATH}"
ENV USER=robot
# Force OpenMPI wrappers to use the Intel backend compilers
ENV OMPI_CC=icx
ENV OMPI_CXX=icpx
ENV OMPI_FC=ifort

##########################
# Miscellaneous settings #
##########################
WORKDIR /tmp

LABEL maintainer="Jian Sun"
LABEL description="AlmaLinux 9.6 container with intel/2024.2.1 software stack for StormSPEED CAM"

CMD ["/bin/bash"]