##############
# Base image #
##############
FROM opensuse/leap:15 AS spack_base

ENV DEBIAN_FRONTEND=noninteractive

# Set up bash environment
SHELL ["/bin/bash", "-c"]

WORKDIR /opt

# Install python3 and git as prerequisite for Spack
# Install the basic compilers (gcc/7.5.0) to build other packages below
# Then we install gcc/12.3.0 and use it as default compiler
RUN zypper --non-interactive refresh && \
    zypper --non-interactive update && \
    zypper --non-interactive install -t pattern devel_basis && \
    zypper --non-interactive install bzip2 libbz2-devel xz xz-devel gmp-devel mpfr-devel mpc-devel zlib-devel && \
    zypper --non-interactive install python3 git make wget gzip unzip curl && \
    zypper --non-interactive install gcc12 gcc12-c++ gcc12-fortran && \
    update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 120 && \
    update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 120 && \
    update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-12 120

# Install AWS CLI v2
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install && \
    rm -rf awscliv2.zip aws && \
    aws --version

# Clone Spack with tag v1.0.0
RUN git clone --depth=2 --branch v1.0.0 https://github.com/spack/spack.git

# Install Python 3.13.5 through Spack (needed for git-fleximod)
RUN . /opt/spack/share/spack/setup-env.sh && \
    spack install python@3.13.5 && \
    update-alternatives --install /usr/bin/python python $(spack location -i python@3.13.5)/bin/python3.13 80 && \
    update-alternatives --install /usr/bin/python3 python3 $(spack location -i python@3.13.5)/bin/python3.13 80

########################
# Build libxml2, cmake #
########################
FROM spack_base AS xml2_cmake

# Install xmllint that is required by CIME
RUN . /opt/spack/share/spack/setup-env.sh && \
    spack install libxml2@2.13.5 && \
    ln -s $(spack location -i libxml2@2.13.5)/bin/xmllint /usr/local/bin/xmllint

RUN . /opt/spack/share/spack/setup-env.sh && \
    spack install cmake@3.31.8 && \
    ln -s $(spack location -i cmake@3.31.8)/bin/cmake /usr/local/bin/cmake

#########################
# Build ucx and openmpi #
#########################
FROM xml2_cmake AS ucx_openmpi

RUN . /opt/spack/share/spack/setup-env.sh && \
    spack install ucx@1.18.1

RUN . /opt/spack/share/spack/setup-env.sh && \
    spack install openmpi@5.0.8 fabrics=cma,ucx ^ucx@1.18.1 && \
    ln -s $(spack location -i openmpi@5.0.8) /usr/local/openmpi

#########################
# Build parallel-netcdf #
#########################
FROM ucx_openmpi AS parallel_netcdf

RUN . /opt/spack/share/spack/setup-env.sh && \
    spack install parallel-netcdf@1.14.0 +cxx +fortran +pic +shared ^openmpi@5.0.8 && \
    ln -s $(spack location -i parallel-netcdf@1.14.0) /usr/local/pnetcdf

################
# Build netCDF #
################
FROM parallel_netcdf AS netcdf

RUN . /opt/spack/share/spack/setup-env.sh && \
    spack install netcdf-c@4.9.2 ^openmpi@5.0.8 ^parallel-netcdf@1.14.0 && \
    ln -s $(spack location -i netcdf-c@4.9.2) /usr/local/netcdf_c

# Install netcdf-fortran; it will install the netcdf-c and openmpi dependency by default
RUN . /opt/spack/share/spack/setup-env.sh && \
    spack install netcdf-fortran@4.6.1 ^netcdf-c@4.9.2 ^openmpi@5.0.8 && \
    ln -s $(spack location -i netcdf-fortran@4.6.1) /usr/local/netcdf_fortran

#############
# Build PIO #
#############
FROM netcdf AS parallelio

# Install parallelio; it will install the parallel-netcdf dependency by default
RUN . /opt/spack/share/spack/setup-env.sh && \
    spack install parallelio@2.6.6 +pnetcdf +fortran +mpi +shared +ncint ^parallel-netcdf@1.14.0 && \
    ln -s $(spack location -i parallelio@2.6.6) /usr/local/pio

##############
# Build ESMF #
##############
FROM parallelio AS esmf

# Install ESMF; it will install its parallelio and parallel-netcdf dependencies by default
RUN . /opt/spack/share/spack/setup-env.sh && \
    spack install esmf@8.8.1 +pnetcdf +mpi +shared ^parallelio@2.6.6 ^parallel-netcdf@1.14.0 && \
    ln -s $(spack location -i esmf@8.8.1) /usr/local/esmf

################
# Build LAPACK #
################
FROM esmf AS final_image

RUN . /opt/spack/share/spack/setup-env.sh && \
    spack install netlib-lapack@3.12.1 && \
    ln -s $(spack location -i netlib-lapack@3.12.1) /usr/local/lapack

################################################
# Set up environment variables for CI workflow #
################################################
ENV CXX=g++
ENV CC=gcc
ENV FC=gfortran
ENV MPI_ROOT="/usr/local/openmpi"
ENV NETCDF_C_PATH="/usr/local/netcdf_c"
ENV NETCDF_FORTRAN_PATH="/usr/local/netcdf_fortran"
ENV PNETCDF="/usr/local/pnetcdf"
ENV PIO="/usr/local/pio"
ENV ESMFMKFILE="/usr/local/esmf/lib/esmf.mk"
ENV LAPACK="/usr/local/lapack"
ENV PIO_VERSION_MAJOR=2
ENV PIO_TYPENAME_VALID_VALUES="netcdf, pnetcdf, netcdf4c, netcdf4p"
ENV PATH="/usr/local:/usr/local/bin:$MPI_ROOT/bin:${PATH}"
ENV USER=robot

##########################
# Miscellaneous settings #
##########################
WORKDIR /tmp

LABEL maintainer="Jian Sun"
LABEL description="openSUSE Leap 15 container with gcc/12.3.0 software stack for StormSPEED CAM"

CMD ["/bin/bash"]