name: Docker container with GNU compiler for CPUs

on:
  push:
    branches:
      - stormspeed
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  docker-build-and-test:
    name: Build and Test - ${{ matrix.dockerfile }}
    runs-on: macos-14 # use GitHub-hosted macOS runners for image built on the aarch64 architecture
    strategy:
      fail-fast: false
      matrix:
        os: [macos-14]
        dockerfile:
          - Dockerfile.gnu
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image which will compile a predefined compset for StormSPEED CAM
        run: docker build -t stormspeed_pr -f dockerfiles/${{ matrix.dockerfile }} .